### ISSUE TITLE
Question: Split project into frontend and backend

### ISSUE THREAD

**Issue by fraherm** [echobind/bisonapp#27]
**Does it make sense split frontend and backend into two different root directories?**
I had a look at the `package.json` and it looks very long. For me it is difficult to distinguish between frontend and backend scripts. Same for the dependencies.

**Comment by cball** [comment]
We did this intentionally, see: https://github.com/echobind/bisonapp#tradeoffs

It's a little bit of a shift, but we do think overall it simplifies some things:
* uses the default Next.js API setup
* no need for yarn workspaces
* feels a little more like a single app rather than two separate parts.

We may change this in the future (especially if everyone hates it!) but I'd like to give this a little more time to get feedback from the community.

If you have ideas on how to handle it that wouldn't complicate things significantly let us know! One that comes to mind is extending the webpack config provided by next to allow for a different folder structure. I'm going to close this for now, but feel free to reopen it in the future.
